// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using session3demo.Data;

namespace session3demo.Migrations
{
    [DbContext(typeof(DemoContext))]
    partial class DemoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("session3demo.Models.Course", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("id")
                        .HasColumnType("int");

                    b.HasKey("Name");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("session3demo.Models.Student", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<double>("Gpa")
                        .HasColumnType("float");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("Name");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("session3demo.Models.StudentCourse", b =>
                {
                    b.Property<string>("studentName")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("courseName")
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("studentName", "courseName");

                    b.HasIndex("courseName");

                    b.ToTable("StudentsCourses");
                });

            modelBuilder.Entity("session3demo.Models.StudentCourse", b =>
                {
                    b.HasOne("session3demo.Models.Course", "Course")
                        .WithMany("StudentCourses")
                        .HasForeignKey("courseName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("session3demo.Models.Student", "Student")
                        .WithMany("Courses")
                        .HasForeignKey("studentName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("session3demo.Models.Course", b =>
                {
                    b.Navigation("StudentCourses");
                });

            modelBuilder.Entity("session3demo.Models.Student", b =>
                {
                    b.Navigation("Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
